version: "3.5"

x-shared-config:
  base: &base
    image: mutations/gatsby:node12.13.1-alpine3.10
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    user: "1069:1420"

  studio: &studio
    <<: *base
    environment:
      - HISTFILE=/app/log/.bash_history
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./studio:/app:cached
      - studio_node_modules:/app/node_modules
    working_dir: /app

  web: &web
    <<: *base
    environment:
      - HISTFILE=/app/log/.bash_history
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./web:/app:cached
      - web_node_modules:/app/node_modules
    working_dir: /app

services:
  app:
    <<: *web
    command: gatsby develop --host 0.0.0.0 --port 8000
    depends_on:
      - proxy
    entrypoint: yarn
    env_file:
      - .env
      - .env.local
    working_dir: /app

  studio:
    <<: *studio
    command: sanity start --host 0.0.0.0 --port 3333
    depends_on:
      - proxy
    entrypoint: yarn
    env_file:
      - .env
      - .env.local
    working_dir: /app

  proxy:
    image: abiosoft/caddy:latest
    ports:
      - "8000:2015"
    volumes:
      - ./certs:/root/certs
      - ./.caddy:/etc/.caddy
      - ./Caddyfile:/etc/Caddyfile

  shell:
    <<: *base
    command: /bin/bash
    working_dir: /app

volumes:
  studio_node_modules:
  web_node_modules:
